MultichoiceCollection.Presentation/Models/ManageViewModels.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Microsoft.Owin.Security;

namespace MultichoiceCollection.Presentation.Models
{
    public class IndexViewModel
    {
        public bool HasPassword { get; set; }
        public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }

    public class ManageLoginsViewModel
    {
        public IList<UserLoginInfo> CurrentLogins { get; set; }
        public IList<AuthenticationDescription> OtherLogins { get; set; }
    }

    public class FactorViewModel
    {
        public string Purpose { get; set; }
    }

    public class SetPasswordViewModel
    {
        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ChangePasswordViewModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class AddPhoneNumberViewModel
    {
        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string Number { get; set; }
    }

    public class VerifyPhoneNumberViewModel
    {
        [Required]
        [Display(Name = "Code")]
        public string Code { get; set; }

        [Required]
        [Phone]
        [Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }
    }

    public class ConfigureTwoFactorViewModel
    {
        public string SelectedProvider { get; set; }
        public ICollection<System.Web.Mvc.SelectListItem> Providers { get; set; }
    }
}

MultichoiceCollection.Presentation/Areas/Admin/Controllers/AdminAccountController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using MultichoiceCollection.Common.Entities;
using MultichoiceCollection.Common.Entities.Base;
using MultichoiceCollection.Common.Entities.Enum;
using MultichoiceCollection.Models.Repositories.Context;
using MultichoiceCollection.Presentation.Attributes;
using MultichoiceCollection.Presentation.Models;
using MultichoiceCollection.Presentation.Services;

namespace MultichoiceCollection.Presentation.Areas.Admin.Controllers
{
   // [AdminAuthorize(Roles = RoleNames.RoleAdmin)]
    public class AdminAccountController : AdminBaseController
    {

        public AdminAccountController()
        {
        }

        public ActionResult Index(int page = 1, int pageSize = 50)
        {
            ViewBag.ViewUsers = "active";
            using (var context = new AppDbContext())
            {
                var offset = (page - 1) * pageSize;
                var users = context.Users.OrderByDescending(u=>u.RegistrationDate).Skip(offset).Take(pageSize).ToList();
                return View("usersList", users);
            }
        }

        public ActionResult Manage(string id)
        {
            using (var context = new AppDbContext())
            {
                var user = context.Users.FirstOrDefault(u => u.Id == id);
                if (user == null) return HttpNotFound();
                var vm = new AdminRegisterViewModel
                {
                    AgentName = user.AgentName,
                    AccountNumber = user.AccountNumber,
                    PhoneNumber = user.PhoneNumber,
                    Email = user.Email,
                    Id = user.Id
                };
                return View(vm);
            }
        }

        [HttpPost]
        public async Task<ActionResult> Update(AdminRegisterViewModel model)
        {
            AddAuditInfo(new AuditTrail
            {
                Title = "Update User Info",
                Detail = $"Account Number: {model.AccountNumber}, Agent Name: {model.AgentName}, Email: {model.Email}, Phone" +
                         $"Number: {model.PhoneNumber}"
            });
            using (var context = new AppDbContext())
            {
                var oldUser = context.Users.FirstOrDefault(u => u.Id == model.Id);
                if (oldUser == null) return HttpNotFound();
                oldUser.PhoneNumber = model.PhoneNumber;
                oldUser.Email = model.Email;
                oldUser.AccountNumber = model.AccountNumber;
                

                var audit = new AuditTrail
                {
                    Date = DateTime.Now,
                    Title = "Updated User Datil",
                    Detail = $"User deatil was changed from [Account Number: {oldUser.AccountNumber}, Agent Name: {oldUser.AgentName}, Email: {oldUser.Email}, Phone " +
                             $"Number: {oldUser.PhoneNumber}] To [Account Number: {model.AccountNumber}, Agent Name: {model.AgentName}, Email: {model.Email}, Phone " +
                             $"Number: {model.PhoneNumber}]",
                    RefUrl = Url.Action("Manage", new {oldUser.Id})
                };
                context.AuditTrails.Add(audit);

                context.SaveChanges();

                ShowMessage("User updated", AlertType.Success);
            }
            return RedirectToAction("Index");
        }


        //
        // GET: /Account/Login
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View(new AdminLoginViewModel());
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        public async Task<ActionResult> Login(AdminLoginViewModel model, string returnUrl)
        {
            AddAuditInfo(new AuditTrail{Title = "Login to Admin Panel", Detail = $"Username: {model.Email}"});
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                // This doesn't count login failures towards account lockout
                // To enable password failures to trigger account lockout, change to shouldLockout: true
                var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, false, shouldLockout: false);
                switch (result)
                {
                    case SignInStatus.Success:
                        using (var context = new AppDbContext())
                        {
                            var user = context.Users.FirstOrDefault(u => u.UserName == model.Email);
                            if (user != null)
                            {
                            }
                        }
                        return RedirectToLocal(returnUrl);
                    case SignInStatus.LockedOut:
                        return View("Lockout");
                    case SignInStatus.RequiresVerification:
                        return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = false });
                    case SignInStatus.Failure:
                    default:
                        ModelState.AddModelError("", "Invalid login attempt.");
                        return View(model);
                }
            }
            catch (Exception exception)
            {
                ViewBag.Error = exception.Message;
            }
            return View(model);
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            return View(new VerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(VerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent: model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }


        //
        // GET: /Account/Register
        public ActionResult Register()
        {
            ViewBag.Register = "current";

            ViewBag.Roles = new SelectList(this.RoleManager.Roles.ToList(), "Name", "Name");
            return View(new AdminRegisterViewModel());
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Register(AdminRegisterViewModel model)
        {
            AddAuditInfo(new AuditTrail
            {
                Title = "Creating New User", Detail = $"Account Number: {model.AccountNumber}, Agent Name: {model.AgentName}, Email: {model.Email}, Phone" +
                                                      $"Number: {model.PhoneNumber}"
            });
            ViewBag.Register = "current";

            if (ModelState.IsValid)
            {
                //generate username MCAGNT002
                var username = GenerateUsername();
                var user = new ApplicationUser {AgentName = model.AgentName,
                    AccountNumber = model.AccountNumber, Email = model.Email,
                    PhoneNumber = model.PhoneNumber, UserName = username,
                    ShouldChangePassword = true, RegistrationDate = DateTime.Now, LastLoginDate = DateTime.Now
                };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    var roleResult = await UserManager.AddToRoleAsync(user.Id, model.Role);

                    var audit = new AuditTrail
                    {
                        Date = DateTime.Now,
                        Title = "Created New User",
                        Detail = $"Created a new user with the name, {user.AgentName}",
                        RefUrl = Url.Action("Manage", new { user.Id })
                    };
                    using (var context = new AppDbContext())
                    {
                        context.AuditTrails.Add(audit);
                        context.SaveChanges();
                    }

                    ShowMessage("Account created successfully", AlertType.Success);
                    return RedirectToAction("Index", new {area = "Admin"});
                }
                ShowMessage("Error in creating account", AlertType.Danger);
                AddErrors(result);
            }

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/Activation.cshtml
@model MultichoiceCollection.Presentation.Models.RegisterViewModel
@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_GuestLayout.cshtml";

}
@using (Html.BeginForm("Activation", "AdminAccount", FormMethod.Post, new { @class = "frm-single" }))
{
    <section class="inside">
        <div class="title">
            <strong>Multichoice</strong> Collection
        </div>
        <!-- /.title -->
        <div class="frm-title">Account Activation</div>
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <div class="frm-input">
            @Html.TextBoxFor(m => m.TransactionPIN, new { @class = "frm-inp", placeholder = "Transaction PIN", @type = "number" })
            <i class="fa fa-bank frm-ico"></i>
        </div>
        <div class="frm-input">
            @Html.TextBoxFor(m => m.Password, new { @class = "frm-inp", placeholder = "Password" })
            <i class="fa fa-lock frm-ico"></i>
        </div>
        <div class="frm-input">
            @Html.TextBoxFor(m => m.ConfirmPassword, new { @class = "frm-inp", placeholder = "Confirm Password" })
            <i class="fa fa-lock frm-ico"></i>
        </div>

        <div class="clearfix margin-bottom-20">
        </div>
        <!-- /.clearfix -->
        <button type="submit" class="frm-submit">Activate<i class="fa fa-lock"></i></button>

        <!-- /.footer -->
    </section>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ConfirmEmail.cshtml
@{
    ViewBag.Title = "Confirm Email";
}

<h2>@ViewBag.Title.</h2>
<div>
    <p>
        Thank you for confirming your email. Please @Html.ActionLink("Click here to Log in", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })
    </p>
</div>

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ExternalLoginConfirmation.cshtml
@model MultichoiceCollection.Presentation.Models.ExternalLoginConfirmationViewModel
@{
    ViewBag.Title = "Register";
}
<h2>@ViewBag.Title.</h2>
<h3>Associate your @ViewBag.LoginProvider account.</h3>

@using (Html.BeginForm("ExternalLoginConfirmation", "AdminAccount", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()

    <h4>Association Form</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <p class="text-info">
        You've successfully authenticated with <strong>@ViewBag.LoginProvider</strong>.
        Please enter a user name for this site below and click the Register button to finish
        logging in.
    </p>
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Email, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Register" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ExternalLoginFailure.cshtml
@{
    ViewBag.Title = "Login Failure";
}

<hgroup>
    <h2>@ViewBag.Title.</h2>
    <h3 class="text-danger">Unsuccessful login with service.</h3>
</hgroup>

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ForgotPassword.cshtml
@model MultichoiceCollection.Presentation.Models.ForgotPasswordViewModel
@{
    ViewBag.Title = "Reset Account password?";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ForgotPassword", "AdminAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ForgotPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Forgot Password Confirmation";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>
<div>
    <p>
        Please check your email to reset your password.
    </p>
</div>
	

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/Login.cshtml
@using MultichoiceCollection.Models
@model MultichoiceCollection.Presentation.Models.AdminLoginViewModel
@{
    ViewBag.Title = "LOG IN";
    Layout = "~/Views/Shared/_GuestLayout.cshtml";

}
@using (Html.BeginForm("Login", "AdminAccount", new {ReturnUrl = ViewBag.ReturnUrl}, FormMethod.Post, new {@class = "frm-single"}))
{
    @Html.AntiForgeryToken()
    <section class="inside">
        <div class="title">
        <strong>Admin</strong> Platform<br/>
            <img src="~@ViewBag.SiteBase/assets/images/logo/heritage-bank.png" width="250" />

        <!-- /.title -->
        <div class="frm-title">Login Admin</div>
        @if (ViewBag.Error != null)
        {
            <div class="alert alert-danger">@ViewBag.Error</div>
        }
        @Html.AntiForgeryToken()
        @Html.ValidationSummary("", new { @class = "text-danger" })
        <!-- /.frm-title -->
        
        <div class="frm-input">
            @Html.TextBoxFor(m => m.Email, new { @class = "frm-inp", placeholder = "Email" })
            <i class="fa fa-bank frm-ico"></i>
 </div>
        <!-- /.frm-input -->
        <div class="frm-input">
            @Html.PasswordFor(m => m.Password, new { @class = "frm-inp", placeholder = "Password" })
            <i class="fa fa-lock frm-ico"></i>
        </div>
        <!-- /.clearfix -->
        <button type="submit" class="frm-submit">Login<i class="fa fa-sign-in"></i></button>

        <!-- /.footer -->
    </section>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/Manage.cshtml
@model MultichoiceCollection.Presentation.Models.AdminRegisterViewModel
@{
    ViewBag.Title = "Manage Account";

}
@section styles{
    <style>
        .frm-single {
            width: 100%;
            max-width: 700px; 
        }
    </style>
}

*@using (Html.BeginForm("Update", "AdminAccount", FormMethod.Post, new { @class = "frm-single" , enctype = "multipart/form-data" }))
 {
     <section class="inside">
         <div class="title">
             <strong>Admin</strong> Area
         </div>
         <!-- /.title -->
         <div class="frm-title">Manage account</div>
         @Html.AntiForgeryToken()
         @Html.ValidationSummary("", new { @class = "text-danger" })
         @Html.HiddenFor(m=>m.Id)
         <div class="frm-input">
             @Html.TextBoxFor(m => m.AgentName, new { @class = "frm-inp", placeholder = "Agent Name" })
             <i class="fa fa-user frm-ico"></i>
         </div>

         <div class="frm-input">
             @Html.TextBoxFor(m => m.AccountNumber, new { @class = "frm-inp", placeholder = "Account Number" })
             <i class="fa fa-user frm-ico"></i>
         </div>
         <div class="frm-input">
             @Html.TextBoxFor(m => m.Email, new { @class = "frm-inp", placeholder = "Email" })
             <i class="fa fa-envelope-o frm-ico"></i>
         </div>
         <div class="frm-input">
             @Html.TextBoxFor(m => m.PhoneNumber, new {@class = "frm-inp", placeholder = "Phone Number"})
             <i class="fa fa-phone frm-ico"></i>
         </div>
        

         <div class="clearfix margin-bottom-20"></div>
         <!-- /.clearfix -->
         <button type="submit" class="frm-submit">Register<i class="fa fa-upload"></i></button>

         <!-- /.footer -->
     </section>
 }


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ResetPassword.cshtml
@model MultichoiceCollection.Presentation.Models.ResetPasswordViewModel
@{
    ViewBag.Title = "Reset password";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("ResetPassword", "AdminAccount", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    @Html.AntiForgeryToken()
    <h4>Reset your password.</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Code)
    <div class="form-group">
        @Html.LabelFor(m => m.Email, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.Password, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "Password" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control", placeholder = "Confirm Password" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Reset" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/ResetPasswordConfirmation.cshtml
@{
    ViewBag.Title = "Password reset was successful.";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
</hgroup>

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/SendCode.cshtml
@model MultichoiceCollection.Presentation.Models.SendCodeViewModel
@{
    ViewBag.Title = "Send";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("SendCode", "AdminAccount", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    @Html.AntiForgeryToken()
    @Html.Hidden("rememberMe", @Model.RememberMe)
    <h4>Send verification code</h4>
    <hr />
    <div class="row">
        <div class="col-md-8">
            Select Two-Factor Authentication Provider:
            @Html.DropDownListFor(model => model.SelectedProvider, Model.Providers)
            <input type="submit" value="Submit" class="btn btn-default" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/VerifyCode.cshtml
@model MultichoiceCollection.Presentation.Models.VerifyCodeViewModel
@{
    ViewBag.Title = "Verify";
}

<h2>@ViewBag.Title.</h2>

@using (Html.BeginForm("VerifyCode", "AdminAccount", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    @Html.AntiForgeryToken()
    @Html.Hidden("provider", @Model.Provider)
    @Html.Hidden("rememberMe", @Model.RememberMe)
    <h4>Enter verification code</h4>
    <hr />
    @Html.ValidationSummary("", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" })
        <div class="col-md-10">
            @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <div class="checkbox">
                @Html.CheckBoxFor(m => m.RememberBrowser)
                @Html.LabelFor(m => m.RememberBrowser)
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" class="btn btn-default" value="Submit" />
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/_ExternalLoginsListPartial.cshtml
@model MultichoiceCollection.Presentation.Models.ExternalLoginListViewModel
@using Microsoft.Owin.Security

<h4>Use another service to log in.</h4>
<hr />
@{
    var loginProviders = Context.GetOwinContext().Authentication.GetExternalAuthenticationTypes();
    if (loginProviders.Count() == 0) {
        <div>
            <p>
                There are no external authentication services configured. See <a href="http://go.microsoft.com/fwlink/?LinkId=403804">this article</a>
                for details on setting up this ASP.NET application to support logging in via external services.
            </p>
        </div>
    }
    else {
        using (Html.BeginForm("ExternalLogin", "AdminAccount", new { ReturnUrl = Model.ReturnUrl })) {
            @Html.AntiForgeryToken()
            <div id="socialLoginList">
                <p>
                    @foreach (AuthenticationDescription p in loginProviders) {
                        <button type="submit" class="btn btn-default" id="@p.AuthenticationType" name="provider" value="@p.AuthenticationType" title="Log in using your @p.Caption account">@p.AuthenticationType</button>
                    }
                </p>
            </div>
        }
    }
}

MultichoiceCollection.Presentation/Areas/Admin/Views/AdminAccount/usersList.cshtml
@model List<MultichoiceCollection.Common.Entities.Base.ApplicationUser>
@{
    ViewBag.Title = "Users";
}

<section class="row small-spacing">
    <div class="box-content">
        <h4 class="box-title">Bouquet Types</h4>

        <!-- /.dropdown js__dropdown -->
        <section class="table-responsive">
            <table class="table table-striped margin-bottom-10">
                <thead>
                <tr>
                    <th>Name</th>
                    <th>Username</th>
                    <th>Email</th>
                    <th>Phone</th>
                    <th>Registration Date</th>
                    <th>Last Login Date</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.AgentName</td>
                        <td>@item.UserName</td>
                        <td>@item.Email</td>
                        <td>@item.PhoneNumber</td>
                        <td>@item.RegistrationDate</td>
                        <td>@item.LastLoginDate</td>
                        <td><a href="@Url.Action("Manage", new{id=item.Id})">Manage</a></td>
                    </tr>
                }


                </tbody>
            </table>
        </section>
        <!-- /.table -->
    </div>
</section>